/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import utilitarios.VerificadoresECorretores;
import beans.ClienteBeans;
import beans.PedidoBeans;
import controller.ClienteController;
import controller.PedidoController;
import java.util.List;
import java.util.ArrayList;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.ListSelectionModel;
import java.util.Date;
import java.text.SimpleDateFormat;
import beans.FuncionarioBeans;
import beans.EntregadorBeans;
import controller.FuncionarioController;
import controller.EntregadorController;


/**
 *
 * @author linux
 */
public class AndamentoDaEntregaGUI extends javax.swing.JInternalFrame {

    MaskFormatter FormatoTelefone;
    ClienteBeans ClienteB;
    ClienteController ClienteC; 
    List<String> Lista;
    DefaultTableModel Modelo;
    List<String> ListaDeItens;
    List<String> ListaDeClientes;
    DecimalFormat FormatoDecimal;
    PedidoController PedidoC;
    PedidoBeans PedidoB;
    FuncionarioBeans FuncionarioB;
    EntregadorBeans EntregadorB;
    Date DataAtual;
    SimpleDateFormat FormatoData, FormatoHora;
    
    String CodigoFuncionario;
    String CodigoEntregador;
    
    /**
     * Creates new form AndamentoDaCozinha
     */
    public AndamentoDaEntregaGUI() {
        initComponents();
        
        
        FormatoDecimal = new DecimalFormat("0.00");
        ClienteB = new ClienteBeans();
        ClienteC = new ClienteController();
        Lista = new ArrayList<>();
        Modelo = (DefaultTableModel)TabelaAndamentoPedidosAEntregar.getModel();
        PedidoC = new PedidoController();
        PedidoB = new PedidoBeans();
        FormatoDecimal = new DecimalFormat("0.00");
        FormatoData = new SimpleDateFormat("yyyy-MM-dd");
        FormatoHora = new SimpleDateFormat("HH:mm:ss");
        
        ListaDeClientes = new ArrayList<>();
        ListaDeItens = new ArrayList<>();
        
        TabelaAndamentoPedidosAEntregar.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        this.CodigoFuncionario = CodigoFuncionario;
        this.CodigoEntregador = CodigoEntregador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1AndamentoDaCozinha = new javax.swing.JTabbedPane();
        jPanelPedidosAbertos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaAndamentoPedidosAEntregar = new javax.swing.JTable();
        jButtonLiberarAndamentoDasEntregasProntas = new javax.swing.JButton();
        jButtonFecharAndamentoDasEntregasAbertas = new javax.swing.JButton();
        jButtonPesquisarAndamentoDasEntregas = new javax.swing.JButton();
        jPanelPedidosProntos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaAndamentoDasEntregasProntas = new javax.swing.JTable();
        jButtonPesquisarPedidosEntregues = new javax.swing.JButton();
        jButtonVoltarAndamentoDasEntregasProntas = new javax.swing.JButton();
        jButtonFecharAndamentoDasEntregasProntas = new javax.swing.JButton();

        setClosable(true);
        setTitle("Andamento da Entrega");

        TabelaAndamentoPedidosAEntregar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Data", "Hora", "Status", "Total", "Cliente", "Funcionário", "Entregador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaAndamentoPedidosAEntregar.getTableHeader().setReorderingAllowed(false);
        TabelaAndamentoPedidosAEntregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaAndamentoPedidosAEntregarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaAndamentoPedidosAEntregar);
        if (TabelaAndamentoPedidosAEntregar.getColumnModel().getColumnCount() > 0) {
            TabelaAndamentoPedidosAEntregar.getColumnModel().getColumn(0).setResizable(false);
            TabelaAndamentoPedidosAEntregar.getColumnModel().getColumn(1).setResizable(false);
            TabelaAndamentoPedidosAEntregar.getColumnModel().getColumn(2).setResizable(false);
            TabelaAndamentoPedidosAEntregar.getColumnModel().getColumn(3).setResizable(false);
            TabelaAndamentoPedidosAEntregar.getColumnModel().getColumn(4).setResizable(false);
            TabelaAndamentoPedidosAEntregar.getColumnModel().getColumn(5).setResizable(false);
            TabelaAndamentoPedidosAEntregar.getColumnModel().getColumn(6).setResizable(false);
            TabelaAndamentoPedidosAEntregar.getColumnModel().getColumn(7).setResizable(false);
        }

        jButtonLiberarAndamentoDasEntregasProntas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/liberarParaEditar.png"))); // NOI18N
        jButtonLiberarAndamentoDasEntregasProntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiberarAndamentoDasEntregasProntasActionPerformed(evt);
            }
        });

        jButtonFecharAndamentoDasEntregasAbertas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar.png"))); // NOI18N
        jButtonFecharAndamentoDasEntregasAbertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharAndamentoDasEntregasAbertasActionPerformed(evt);
            }
        });

        jButtonPesquisarAndamentoDasEntregas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jButtonPesquisarAndamentoDasEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarAndamentoDasEntregasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPedidosAbertosLayout = new javax.swing.GroupLayout(jPanelPedidosAbertos);
        jPanelPedidosAbertos.setLayout(jPanelPedidosAbertosLayout);
        jPanelPedidosAbertosLayout.setHorizontalGroup(
            jPanelPedidosAbertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPedidosAbertosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPedidosAbertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPedidosAbertosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonLiberarAndamentoDasEntregasProntas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFecharAndamentoDasEntregasAbertas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addContainerGap())
            .addGroup(jPanelPedidosAbertosLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButtonPesquisarAndamentoDasEntregas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1021, Short.MAX_VALUE))
        );
        jPanelPedidosAbertosLayout.setVerticalGroup(
            jPanelPedidosAbertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPedidosAbertosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonPesquisarAndamentoDasEntregas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addGroup(jPanelPedidosAbertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLiberarAndamentoDasEntregasProntas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFecharAndamentoDasEntregasAbertas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        jTabbedPane1AndamentoDaCozinha.addTab("Pedidos a Entregar", jPanelPedidosAbertos);

        TabelaAndamentoDasEntregasProntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Descrição", "Funcionário", "Entregador", "Status", "Hora", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaAndamentoDasEntregasProntas.getTableHeader().setReorderingAllowed(false);
        TabelaAndamentoDasEntregasProntas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaAndamentoDasEntregasProntasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelaAndamentoDasEntregasProntas);
        if (TabelaAndamentoDasEntregasProntas.getColumnModel().getColumnCount() > 0) {
            TabelaAndamentoDasEntregasProntas.getColumnModel().getColumn(0).setResizable(false);
            TabelaAndamentoDasEntregasProntas.getColumnModel().getColumn(1).setResizable(false);
            TabelaAndamentoDasEntregasProntas.getColumnModel().getColumn(2).setResizable(false);
            TabelaAndamentoDasEntregasProntas.getColumnModel().getColumn(3).setResizable(false);
            TabelaAndamentoDasEntregasProntas.getColumnModel().getColumn(4).setResizable(false);
            TabelaAndamentoDasEntregasProntas.getColumnModel().getColumn(5).setResizable(false);
            TabelaAndamentoDasEntregasProntas.getColumnModel().getColumn(6).setResizable(false);
        }

        jButtonPesquisarPedidosEntregues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jButtonPesquisarPedidosEntregues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarPedidosEntreguesActionPerformed(evt);
            }
        });

        jButtonVoltarAndamentoDasEntregasProntas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N

        jButtonFecharAndamentoDasEntregasProntas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar.png"))); // NOI18N
        jButtonFecharAndamentoDasEntregasProntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharAndamentoDasEntregasProntasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPedidosProntosLayout = new javax.swing.GroupLayout(jPanelPedidosProntos);
        jPanelPedidosProntos.setLayout(jPanelPedidosProntosLayout);
        jPanelPedidosProntosLayout.setHorizontalGroup(
            jPanelPedidosProntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1117, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPedidosProntosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVoltarAndamentoDasEntregasProntas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFecharAndamentoDasEntregasProntas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelPedidosProntosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButtonPesquisarPedidosEntregues, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPedidosProntosLayout.setVerticalGroup(
            jPanelPedidosProntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPedidosProntosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPesquisarPedidosEntregues, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(jPanelPedidosProntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltarAndamentoDasEntregasProntas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFecharAndamentoDasEntregasProntas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jTabbedPane1AndamentoDaCozinha.addTab("Pedidos Entregue", jPanelPedidosProntos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1AndamentoDaCozinha)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1AndamentoDaCozinha)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharAndamentoDasEntregasProntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharAndamentoDasEntregasProntasActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFecharAndamentoDasEntregasProntasActionPerformed

    private void jButtonFecharAndamentoDasEntregasAbertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharAndamentoDasEntregasAbertasActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFecharAndamentoDasEntregasAbertasActionPerformed

    private void jButtonLiberarAndamentoDasEntregasProntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiberarAndamentoDasEntregasProntasActionPerformed
      PedidoC.editarDadosPedidosEntregues(PedidoB);
      Modelo.setNumRows(0);
     
    }//GEN-LAST:event_jButtonLiberarAndamentoDasEntregasProntasActionPerformed

    private void TabelaAndamentoPedidosAEntregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaAndamentoPedidosAEntregarMouseClicked
        PedidoB = PedidoC.controlePreenchimentoPedidosAEntregar(Integer.parseInt(Modelo.getValueAt(TabelaAndamentoPedidosAEntregar.getSelectedRow(), 0).toString()));
        
    }//GEN-LAST:event_TabelaAndamentoPedidosAEntregarMouseClicked

    private void TabelaAndamentoDasEntregasProntasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaAndamentoDasEntregasProntasMouseClicked
        PedidoB = PedidoC.controlePreenchimento(Integer.parseInt(Modelo.getValueAt(TabelaAndamentoDasEntregasProntas.getSelectedRow(), 0).toString()));
    }//GEN-LAST:event_TabelaAndamentoDasEntregasProntasMouseClicked

    private void jButtonPesquisarAndamentoDasEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarAndamentoDasEntregasActionPerformed
        Modelo.setNumRows(0);
        PedidoC.controlePesquisaPedidosAEntregar(Modelo);
    }//GEN-LAST:event_jButtonPesquisarAndamentoDasEntregasActionPerformed

    private void jButtonPesquisarPedidosEntreguesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarPedidosEntreguesActionPerformed
               Modelo.setNumRows(0);
               PedidoC.controlePesquisaPedidosEntregues(Modelo);
    }//GEN-LAST:event_jButtonPesquisarPedidosEntreguesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaAndamentoDasEntregasProntas;
    private javax.swing.JTable TabelaAndamentoPedidosAEntregar;
    private javax.swing.JButton jButtonFecharAndamentoDasEntregasAbertas;
    private javax.swing.JButton jButtonFecharAndamentoDasEntregasProntas;
    private javax.swing.JButton jButtonLiberarAndamentoDasEntregasProntas;
    private javax.swing.JButton jButtonPesquisarAndamentoDasEntregas;
    private javax.swing.JButton jButtonPesquisarPedidosEntregues;
    private javax.swing.JButton jButtonVoltarAndamentoDasEntregasProntas;
    private javax.swing.JPanel jPanelPedidosAbertos;
    private javax.swing.JPanel jPanelPedidosProntos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1AndamentoDaCozinha;
    // End of variables declaration//GEN-END:variables
}
