/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import utilitarios.VerificadoresECorretores;
import beans.ClienteBeans;
import beans.PedidoBeans;
import controller.ClienteController;
import controller.PedidoController;
import java.util.List;
import java.util.ArrayList;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.ListSelectionModel;
import java.util.Date;
import java.text.SimpleDateFormat;
import beans.FuncionarioBeans;
import beans.EntregadorBeans;
import controller.FuncionarioController;
import controller.EntregadorController;


/**
 *
 * @author linux
 */
public class AndamentoDaCozinhaGUI extends javax.swing.JInternalFrame {

    MaskFormatter FormatoTelefone;
    ClienteBeans ClienteB;
    ClienteController ClienteC; 
    List<String> Lista;
    DefaultTableModel Modelo;
    List<String> ListaDeItens;
    List<String> ListaDeClientes;
    DecimalFormat FormatoDecimal;
    PedidoController PedidoC;
    PedidoBeans PedidoB;
    FuncionarioBeans FuncionarioB;
    EntregadorBeans EntregadorB;
    Date DataAtual;
    SimpleDateFormat FormatoData, FormatoHora;
    
    String CodigoFuncionario;
    String CodigoEntregador;
    
    /**
     * Creates new form AndamentoDaCozinha
     */
    public AndamentoDaCozinhaGUI() {
        initComponents();
        
        
        FormatoDecimal = new DecimalFormat("0.00");
        ClienteB = new ClienteBeans();
        ClienteC = new ClienteController();
        Lista = new ArrayList<>();
        Modelo = (DefaultTableModel)TabelaPedidosAbertos.getModel();
        PedidoC = new PedidoController();
        PedidoB = new PedidoBeans();
        FormatoDecimal = new DecimalFormat("0.00");
        FormatoData = new SimpleDateFormat("yyyy-MM-dd");
        FormatoHora = new SimpleDateFormat("HH:mm:ss");
        
        ListaDeClientes = new ArrayList<>();
        ListaDeItens = new ArrayList<>();
        
        TabelaPedidosAbertos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        this.CodigoFuncionario = CodigoFuncionario;
        this.CodigoEntregador = CodigoEntregador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1AndamentoDaCozinha = new javax.swing.JTabbedPane();
        jPanelPedidosAbertos = new javax.swing.JPanel();
        jButtonLiberarPedidoaAEntregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaPedidosAbertos = new javax.swing.JTable();
        jButtonFecharPedidosAEntregar = new javax.swing.JButton();
        jButtonPesquisarPedidosAbertos = new javax.swing.JButton();
        jPanelPedidosProntos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaPedidosAEntregar = new javax.swing.JTable();
        jButtonPesquisarPedidosAEntregar = new javax.swing.JButton();
        jButtonVoltarPedidosAbertos = new javax.swing.JButton();
        jButtonFecharPedidosProntos = new javax.swing.JButton();

        setClosable(true);
        setTitle("Andamento da Cozinha");

        jButtonLiberarPedidoaAEntregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/liberarParaEditar.png"))); // NOI18N
        jButtonLiberarPedidoaAEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiberarPedidoaAEntregarActionPerformed(evt);
            }
        });

        TabelaPedidosAbertos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Data", "Hora", "Status", "Total", "Cliente", "Funcionário", "Entregador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaPedidosAbertos.getTableHeader().setReorderingAllowed(false);
        TabelaPedidosAbertos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaPedidosAbertosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaPedidosAbertos);
        if (TabelaPedidosAbertos.getColumnModel().getColumnCount() > 0) {
            TabelaPedidosAbertos.getColumnModel().getColumn(0).setResizable(false);
            TabelaPedidosAbertos.getColumnModel().getColumn(1).setResizable(false);
            TabelaPedidosAbertos.getColumnModel().getColumn(2).setResizable(false);
            TabelaPedidosAbertos.getColumnModel().getColumn(3).setResizable(false);
            TabelaPedidosAbertos.getColumnModel().getColumn(4).setResizable(false);
            TabelaPedidosAbertos.getColumnModel().getColumn(5).setResizable(false);
            TabelaPedidosAbertos.getColumnModel().getColumn(6).setResizable(false);
            TabelaPedidosAbertos.getColumnModel().getColumn(7).setResizable(false);
        }

        jButtonFecharPedidosAEntregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar.png"))); // NOI18N
        jButtonFecharPedidosAEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharPedidosAEntregarActionPerformed(evt);
            }
        });

        jButtonPesquisarPedidosAbertos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jButtonPesquisarPedidosAbertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarPedidosAbertosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPedidosAbertosLayout = new javax.swing.GroupLayout(jPanelPedidosAbertos);
        jPanelPedidosAbertos.setLayout(jPanelPedidosAbertosLayout);
        jPanelPedidosAbertosLayout.setHorizontalGroup(
            jPanelPedidosAbertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPedidosAbertosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPedidosAbertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPedidosAbertosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonLiberarPedidoaAEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFecharPedidosAEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addContainerGap())
            .addGroup(jPanelPedidosAbertosLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButtonPesquisarPedidosAbertos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPedidosAbertosLayout.setVerticalGroup(
            jPanelPedidosAbertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPedidosAbertosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPesquisarPedidosAbertos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addGroup(jPanelPedidosAbertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLiberarPedidoaAEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFecharPedidosAEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        jTabbedPane1AndamentoDaCozinha.addTab("Pedidos Abertos", jPanelPedidosAbertos);

        TabelaPedidosAEntregar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Descrição", "Funcionário", "Entregador", "Status", "Hora", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaPedidosAEntregar.getTableHeader().setReorderingAllowed(false);
        TabelaPedidosAEntregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaPedidosAEntregarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelaPedidosAEntregar);
        if (TabelaPedidosAEntregar.getColumnModel().getColumnCount() > 0) {
            TabelaPedidosAEntregar.getColumnModel().getColumn(0).setResizable(false);
            TabelaPedidosAEntregar.getColumnModel().getColumn(1).setResizable(false);
            TabelaPedidosAEntregar.getColumnModel().getColumn(2).setResizable(false);
            TabelaPedidosAEntregar.getColumnModel().getColumn(3).setResizable(false);
            TabelaPedidosAEntregar.getColumnModel().getColumn(4).setResizable(false);
            TabelaPedidosAEntregar.getColumnModel().getColumn(5).setResizable(false);
            TabelaPedidosAEntregar.getColumnModel().getColumn(6).setResizable(false);
        }

        jButtonPesquisarPedidosAEntregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jButtonPesquisarPedidosAEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarPedidosAEntregarActionPerformed(evt);
            }
        });

        jButtonVoltarPedidosAbertos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        jButtonVoltarPedidosAbertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarPedidosAbertosActionPerformed(evt);
            }
        });

        jButtonFecharPedidosProntos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar.png"))); // NOI18N
        jButtonFecharPedidosProntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharPedidosProntosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPedidosProntosLayout = new javax.swing.GroupLayout(jPanelPedidosProntos);
        jPanelPedidosProntos.setLayout(jPanelPedidosProntosLayout);
        jPanelPedidosProntosLayout.setHorizontalGroup(
            jPanelPedidosProntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPedidosProntosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVoltarPedidosAbertos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFecharPedidosProntos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelPedidosProntosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButtonPesquisarPedidosAEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPedidosProntosLayout.setVerticalGroup(
            jPanelPedidosProntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPedidosProntosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPesquisarPedidosAEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(jPanelPedidosProntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltarPedidosAbertos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFecharPedidosProntos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jTabbedPane1AndamentoDaCozinha.addTab("Pedidos Prontos", jPanelPedidosProntos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1AndamentoDaCozinha)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1AndamentoDaCozinha)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharPedidosProntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharPedidosProntosActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFecharPedidosProntosActionPerformed

    private void jButtonFecharPedidosAEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharPedidosAEntregarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFecharPedidosAEntregarActionPerformed

    private void jButtonLiberarPedidoaAEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiberarPedidoaAEntregarActionPerformed
      PedidoC.editarDadosPedidosAEntregar(PedidoB);
      Modelo.setNumRows(0);
     
    }//GEN-LAST:event_jButtonLiberarPedidoaAEntregarActionPerformed

    private void TabelaPedidosAbertosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaPedidosAbertosMouseClicked
        PedidoB = PedidoC.controlePreenchimentoPedidosAbertos(Integer.parseInt(Modelo.getValueAt(TabelaPedidosAbertos.getSelectedRow(), 0).toString()));
        
    }//GEN-LAST:event_TabelaPedidosAbertosMouseClicked

    private void TabelaPedidosAEntregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaPedidosAEntregarMouseClicked
        PedidoB = PedidoC.controlePreenchimentoPedidosAEntregar(Integer.parseInt(Modelo.getValueAt(TabelaPedidosAEntregar.getSelectedRow(), 0).toString()));
    }//GEN-LAST:event_TabelaPedidosAEntregarMouseClicked

    private void jButtonVoltarPedidosAbertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarPedidosAbertosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVoltarPedidosAbertosActionPerformed

    private void jButtonPesquisarPedidosAbertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarPedidosAbertosActionPerformed
        Modelo.setNumRows(0);
        PedidoC.controlePesquisaPedidosAbertos(Modelo);
    }//GEN-LAST:event_jButtonPesquisarPedidosAbertosActionPerformed

    private void jButtonPesquisarPedidosAEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarPedidosAEntregarActionPerformed
        Modelo.setNumRows(0);
        PedidoC.controlePesquisaPedidosAEntregar(Modelo);
    }//GEN-LAST:event_jButtonPesquisarPedidosAEntregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaPedidosAEntregar;
    private javax.swing.JTable TabelaPedidosAbertos;
    private javax.swing.JButton jButtonFecharPedidosAEntregar;
    private javax.swing.JButton jButtonFecharPedidosProntos;
    private javax.swing.JButton jButtonLiberarPedidoaAEntregar;
    private javax.swing.JButton jButtonPesquisarPedidosAEntregar;
    private javax.swing.JButton jButtonPesquisarPedidosAbertos;
    private javax.swing.JButton jButtonVoltarPedidosAbertos;
    private javax.swing.JPanel jPanelPedidosAbertos;
    private javax.swing.JPanel jPanelPedidosProntos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1AndamentoDaCozinha;
    // End of variables declaration//GEN-END:variables
}
