/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import beans.CardapioBeans;
import controller.CardapioController;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edson Dias
 */
public class CardapioGUI extends javax.swing.JInternalFrame {

    DefaultTableModel Modelo;
    CardapioController CardapioC;
    CardapioBeans CardapioB;
    DecimalFormat FormatoDecimal;
     
    
    /**
     * Creates new form FuncionarioGUI
     */
    public CardapioGUI() {
        initComponents();
        
        BotaoCadastrar.setEnabled(false);
        jButtonLiberar.setEnabled(false);
        BotaoEditar.setEnabled(false);
        
        jTextFieldCodigo.setEditable(false);
        
        Modelo = (DefaultTableModel)Tabela.getModel();
        
        habilitaTudo(false);
        
        CardapioC = new CardapioController();
        
        CardapioB = new CardapioBeans();
        
        FormatoDecimal = new DecimalFormat("0.00");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelValor = new javax.swing.JLabel();
        jSeparatorCodigo = new javax.swing.JSeparator();
        jSeparatorPesquisar = new javax.swing.JSeparator();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jLabelPesquisar = new javax.swing.JLabel();
        jSeparatorFormulario = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jSeparatorBotoes = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jLabelDescricao1 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox();
        jLabelTipo1 = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        BotaoNovo = new javax.swing.JButton();
        BotaoCadastrar = new javax.swing.JButton();
        jButtonLiberar = new javax.swing.JButton();
        BotaoEditar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Manutenção de Cardápio");
        getContentPane().setLayout(null);

        jLabelCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCodigo.setText("Código");
        getContentPane().add(jLabelCodigo);
        jLabelCodigo.setBounds(0, 0, 440, 17);

        jTextFieldCodigo.setEditable(false);
        jTextFieldCodigo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldCodigo.setForeground(new java.awt.Color(255, 51, 51));
        jTextFieldCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCodigo.setDisabledTextColor(new java.awt.Color(255, 0, 51));
        jTextFieldCodigo.setEnabled(false);
        jTextFieldCodigo.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(0, 20, 440, 21);

        jLabelValor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelValor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cifraoValor.png"))); // NOI18N
        getContentPane().add(jLabelValor);
        jLabelValor.setBounds(200, 160, 50, 40);
        getContentPane().add(jSeparatorCodigo);
        jSeparatorCodigo.setBounds(0, 51, 440, 2);
        getContentPane().add(jSeparatorPesquisar);
        jSeparatorPesquisar.setBounds(0, 260, 440, 2);

        jTextFieldPesquisar.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldPesquisar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });
        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(90, 220, 360, 30);

        jLabelPesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        getContentPane().add(jLabelPesquisar);
        jLabelPesquisar.setBounds(40, 207, 50, 40);
        getContentPane().add(jSeparatorFormulario);
        jSeparatorFormulario.setBounds(0, 200, 440, 2);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Tipo", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.getTableHeader().setReorderingAllowed(false);
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabelaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(0).setResizable(false);
            Tabela.getColumnModel().getColumn(1).setResizable(false);
            Tabela.getColumnModel().getColumn(2).setResizable(false);
            Tabela.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 270, 440, 120);
        getContentPane().add(jSeparatorBotoes);
        jSeparatorBotoes.setBounds(0, 400, 440, 10);

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescricao);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(80, 80, 350, 80);

        jLabelDescricao1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelDescricao1.setText("Descrição:");
        getContentPane().add(jLabelDescricao1);
        jLabelDescricao1.setBounds(0, 73, 80, 17);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pizza", "Refrigerante" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipo);
        jComboBoxTipo.setBounds(80, 170, 110, 20);

        jLabelTipo1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTipo1.setText("Tipo:");
        getContentPane().add(jLabelTipo1);
        jLabelTipo1.setBounds(40, 170, 40, 17);

        jTextFieldValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldValorFocusLost(evt);
            }
        });
        getContentPane().add(jTextFieldValor);
        jTextFieldValor.setBounds(250, 160, 180, 40);

        BotaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        BotaoNovo.setToolTipText("Habilita o formulário para receber novos dados");
        BotaoNovo.setAutoscrolls(true);
        BotaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovoActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoNovo);
        BotaoNovo.setBounds(40, 430, 50, 49);

        BotaoCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvarV2.png"))); // NOI18N
        BotaoCadastrar.setToolTipText("Cadastro de um novo cliente");
        BotaoCadastrar.setAutoscrolls(true);
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCadastrar);
        BotaoCadastrar.setBounds(100, 430, 50, 49);

        jButtonLiberar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/liberarParaEditar.png"))); // NOI18N
        jButtonLiberar.setToolTipText("Libera os campos para edição");
        jButtonLiberar.setAutoscrolls(true);
        jButtonLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiberarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLiberar);
        jButtonLiberar.setBounds(160, 430, 50, 49);

        BotaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        BotaoEditar.setToolTipText("Para editar alguma informação do cliente");
        BotaoEditar.setAutoscrolls(true);
        BotaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEditar);
        BotaoEditar.setBounds(220, 430, 52, 49);

        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar.png"))); // NOI18N
        jButtonFechar.setAutoscrolls(true);
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFechar);
        jButtonFechar.setBounds(280, 430, 50, 50);

        setBounds(0, 0, 450, 538);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    private void jTextFieldPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarKeyPressed

    private void jTextFieldPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyReleased
        BotaoCadastrar.setEnabled(false);
        jButtonLiberar.setEnabled(true);
        BotaoEditar.setEnabled(true);
        
        Modelo.setNumRows(0);
        CardapioC.controlePesquisa(jTextFieldPesquisar.getText(), Modelo);
    }//GEN-LAST:event_jTextFieldPesquisarKeyReleased

    private void TabelaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMousePressed
       CardapioB = CardapioC.controlePreenchimento(Integer.parseInt(Modelo.getValueAt(Tabela.getSelectedRow(), 0).toString()));
       jTextFieldCodigo.setText(CardapioB.getCar_Cod() + "");
       jTextAreaDescricao.setText(CardapioB.getCar_Descricao() + "");
       jComboBoxTipo.setSelectedItem(CardapioB.getCar_Tipo());
       jTextFieldValor.setText(CardapioB.getCar_Valor() + "");
    }//GEN-LAST:event_TabelaMousePressed

    private void jTextFieldValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldValorFocusLost
        // TODO add your handling code here:
        try {
            double Verifica = Double.parseDouble(jTextFieldValor.getText().replace(",", "."));
            jTextFieldValor.setText(FormatoDecimal.format(Verifica).replace(",", "."));
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "O Campo Valor deve conter apenas números!!!", "Erro de preenchimento", 0, new ImageIcon("Imagens/cancelar.png"));
            jTextFieldValor.setText("");
            jTextFieldValor.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldValorFocusLost

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void BotaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoActionPerformed
        Modelo.setRowCount(0);  //Limpa tabela
        BotaoCadastrar.setEnabled(true);
        jButtonLiberar.setEnabled(false);
        BotaoEditar.setEnabled(false);
        
        habilitaTudo(true);
        jTextAreaDescricao.requestFocus(); // Foco descriçoão
        jTextFieldCodigo.setText(CardapioC.controleDeCodigo());
        limpaNovo();
    }//GEN-LAST:event_BotaoNovoActionPerformed

    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarActionPerformed
        //Cadastrar
        capturaBeans();
        if(CardapioC.verificaDados(CardapioB, jTextFieldValor.getText())) {
            limparTudo();
            habilitaTudo(false);
        }
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    private void jButtonLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiberarActionPerformed
        // TODO add your handling code here:
        BotaoCadastrar.setEnabled(false);
        BotaoEditar.setEnabled(true);
        
        habilitaTudo(true);
        jTextAreaDescricao.requestFocus();
        
    }//GEN-LAST:event_jButtonLiberarActionPerformed

    private void BotaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditarActionPerformed
        // TODO add your handling code here:
        capturaBeans();
        if(CardapioC.verificaDadosParaEditar(CardapioB, jTextFieldValor.getText())) {
            limparTudo();
            habilitaTudo(false);
        }
    }//GEN-LAST:event_BotaoEditarActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JButton BotaoEditar;
    private javax.swing.JButton BotaoNovo;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLiberar;
    private javax.swing.JComboBox jComboBoxTipo;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDescricao1;
    private javax.swing.JLabel jLabelPesquisar;
    private javax.swing.JLabel jLabelTipo1;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparatorBotoes;
    private javax.swing.JSeparator jSeparatorCodigo;
    private javax.swing.JSeparator jSeparatorFormulario;
    private javax.swing.JSeparator jSeparatorPesquisar;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables

final void habilitaTudo(boolean Valor) {
     jTextAreaDescricao.setEditable(Valor);
     jComboBoxTipo.setEnabled(Valor);
     jTextFieldValor.setEnabled(Valor);
    }

final void limpaNovo() {
    jTextAreaDescricao.setText("");
    jComboBoxTipo.setSelectedIndex(0);
    jTextFieldValor.setText("");
    }

final void limparTudo() {
    jTextFieldCodigo.setText("");
    jTextAreaDescricao.setText("");
    jComboBoxTipo.setSelectedIndex(0);
    jTextFieldValor.setText("");
    }

final CardapioBeans capturaBeans() {
    CardapioB.setCar_Cod(Integer.parseInt(jTextFieldCodigo.getText()));
    CardapioB.setCar_Descricao(jTextAreaDescricao.getText());
    CardapioB.setCar_Tipo(jComboBoxTipo.getSelectedItem().toString());
    CardapioB.setCar_Valor(Double.parseDouble(jTextFieldValor.getText()));
    
    return CardapioB;
    
    }
}
