/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import beans.EntregadorBeans;
import controller.EntregadorController;
import javax.swing.table.DefaultTableModel;
import utilitarios.VerificadoresECorretores;

/**
 *
 * @author Edson Dias
 */
public class EntregadorGUI extends javax.swing.JInternalFrame {

    DefaultTableModel Modelo;
    EntregadorController EntregadorC;
    EntregadorBeans EntregadorB;
     
    
    /**
     * Creates new form FuncionarioGUI
     */
    public EntregadorGUI() {
        initComponents();
        
        Modelo = (DefaultTableModel)Tabela.getModel();
        
        jTextFieldCodigo.setEditable(false);
        jTextFieldData.setEditable(false);
        
        BotaoCadastrar.setEnabled(false);
        jButtonLiberar.setEnabled(false);
        BotaoEditar.setEnabled(false);
        
        jTextFieldData.setText(VerificadoresECorretores.retornoDeDataAtual());
        
        habilitaTudo(false);
        
        EntregadorC = new EntregadorController();
        
        EntregadorB = new EntregadorBeans();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jSeparatorCodigo = new javax.swing.JSeparator();
        jTextFieldData = new javax.swing.JTextField();
        jLabelData = new javax.swing.JLabel();
        jSeparatorPesquisar = new javax.swing.JSeparator();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jLabelPesquisar = new javax.swing.JLabel();
        jSeparatorFormulario = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jSeparatorBotoes = new javax.swing.JSeparator();
        BotaoNovo = new javax.swing.JButton();
        BotaoCadastrar = new javax.swing.JButton();
        jButtonLiberar = new javax.swing.JButton();
        BotaoEditar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Manutenção de Entregadores");
        getContentPane().setLayout(null);

        jLabelCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCodigo.setText("Código");
        getContentPane().add(jLabelCodigo);
        jLabelCodigo.setBounds(0, 0, 440, 17);

        jTextFieldCodigo.setEditable(false);
        jTextFieldCodigo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldCodigo.setForeground(new java.awt.Color(255, 51, 51));
        jTextFieldCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCodigo.setDisabledTextColor(new java.awt.Color(255, 0, 51));
        jTextFieldCodigo.setEnabled(false);
        jTextFieldCodigo.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(0, 20, 440, 21);

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(63, 60, 377, 30);

        jLabelNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNome.setText("Nome:");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(0, 73, 53, 17);
        getContentPane().add(jSeparatorCodigo);
        jSeparatorCodigo.setBounds(0, 51, 440, 2);

        jTextFieldData.setEditable(false);
        jTextFieldData.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldData);
        jTextFieldData.setBounds(200, 110, 140, 30);

        jLabelData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dataCalendario.png"))); // NOI18N
        getContentPane().add(jLabelData);
        jLabelData.setBounds(140, 100, 50, 50);
        getContentPane().add(jSeparatorPesquisar);
        jSeparatorPesquisar.setBounds(10, 247, 430, 2);

        jTextFieldPesquisar.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldPesquisar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });
        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(94, 206, 346, 30);

        jLabelPesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        getContentPane().add(jLabelPesquisar);
        jLabelPesquisar.setBounds(30, 190, 50, 50);
        getContentPane().add(jSeparatorFormulario);
        jSeparatorFormulario.setBounds(0, 189, 440, 2);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.getTableHeader().setReorderingAllowed(false);
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabelaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(0).setResizable(false);
            Tabela.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 267, 440, 120);
        getContentPane().add(jSeparatorBotoes);
        jSeparatorBotoes.setBounds(0, 398, 440, 2);

        BotaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        BotaoNovo.setToolTipText("Habilita o formulário para receber novos dados");
        BotaoNovo.setAutoscrolls(true);
        BotaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovoActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoNovo);
        BotaoNovo.setBounds(40, 420, 50, 49);

        BotaoCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvarV2.png"))); // NOI18N
        BotaoCadastrar.setToolTipText("Cadastro de um novo cliente");
        BotaoCadastrar.setAutoscrolls(true);
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCadastrar);
        BotaoCadastrar.setBounds(100, 420, 50, 49);

        jButtonLiberar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/liberarParaEditar.png"))); // NOI18N
        jButtonLiberar.setToolTipText("Libera os campos para edição");
        jButtonLiberar.setAutoscrolls(true);
        jButtonLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiberarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLiberar);
        jButtonLiberar.setBounds(160, 420, 50, 49);

        BotaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        BotaoEditar.setToolTipText("Para editar alguma informação do cliente");
        BotaoEditar.setAutoscrolls(true);
        BotaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEditar);
        BotaoEditar.setBounds(220, 420, 52, 49);

        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar.png"))); // NOI18N
        jButtonFechar.setAutoscrolls(true);
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFechar);
        jButtonFechar.setBounds(280, 420, 50, 50);

        setBounds(0, 0, 450, 528);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    private void jTextFieldPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarKeyPressed

    private void jTextFieldPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyReleased
        BotaoCadastrar.setEnabled(false);
        jButtonLiberar.setEnabled(true);
        BotaoEditar.setEnabled(true);
        
        Modelo.setNumRows(0);
         EntregadorC.controlePesquisa(jTextFieldPesquisar.getText(), Modelo);
    }//GEN-LAST:event_jTextFieldPesquisarKeyReleased

    private void TabelaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMousePressed
        EntregadorB = EntregadorC.controlePreenchimento(Integer.parseInt(Modelo.getValueAt(Tabela.getSelectedRow(), 0).toString()));
        jTextFieldCodigo.setText(EntregadorB.getEnt_cod() + "");
        jTextFieldNome.setText(EntregadorB.getEnt_nome() + "");
        jTextFieldData.setText(EntregadorB.getEnt_dataCad() + "");
    }//GEN-LAST:event_TabelaMousePressed

    private void BotaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoActionPerformed
        Modelo.setRowCount(0);  //Limpa tabela
        BotaoCadastrar.setEnabled(true);
        jButtonLiberar.setEnabled(false);
        BotaoEditar.setEnabled(false);
                        
        habilitaTudo(true);
        jTextFieldData.setText(VerificadoresECorretores.retornoDeDataAtual());
        jTextFieldNome.requestFocus(); // Foco no nome
        jTextFieldCodigo.setText(EntregadorC.controleDeCodigo());
        limparNovo();
    }//GEN-LAST:event_BotaoNovoActionPerformed

    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarActionPerformed
        //Cadastrar
        capturaBeans();
        if(EntregadorC.verificaDados(EntregadorB)) {
            limparTudo();
            habilitaTudo(false);
        }
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    private void jButtonLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiberarActionPerformed
        // TODO add your handling code here:
        BotaoCadastrar.setEnabled(false);
        BotaoEditar.setEnabled(true);
        
        habilitaTudo(true);
        jTextFieldNome.requestFocus();
    }//GEN-LAST:event_jButtonLiberarActionPerformed

    private void BotaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditarActionPerformed
        // TODO add your handling code here:
        capturaBeans();
        if(EntregadorC.verificaDadosParaEditar(EntregadorB)) {
            limparTudo();
            habilitaTudo(false);
        }
    }//GEN-LAST:event_BotaoEditarActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JButton BotaoEditar;
    private javax.swing.JButton BotaoNovo;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLiberar;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparatorBotoes;
    private javax.swing.JSeparator jSeparatorCodigo;
    private javax.swing.JSeparator jSeparatorFormulario;
    private javax.swing.JSeparator jSeparatorPesquisar;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables

final void habilitaTudo(boolean Valor) {
     jTextFieldNome.setEditable(Valor);
   }

final void limparNovo() {
    jTextFieldNome.setText("");
   }

final void limparTudo() {
    jTextFieldCodigo.setText("");
    jTextFieldNome.setText("");
    jTextFieldData.setText("");
    }

final EntregadorBeans capturaBeans() {
    EntregadorB.setEnt_cod(Integer.parseInt(jTextFieldCodigo.getText()));
    EntregadorB.setEnt_nome(jTextFieldNome.getText());
    EntregadorB.setEnt_dataCad(jTextFieldData.getText());
    
    return EntregadorB;
}
}
