/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import beans.FuncionarioBeans;
import controller.FuncionarioController;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import utilitarios.VerificadoresECorretores;
/**
 *
 * @author Edson Dias
 */
public class FuncionarioGUI extends javax.swing.JInternalFrame {

    MaskFormatter FormatoTelefone;
    
    DefaultTableModel Modelo;
    FuncionarioController FuncionarioC;
    FuncionarioBeans FuncionarioB;
     
    
    /**
     * Creates new form FuncionarioGUI
     */
    public FuncionarioGUI() {
        initComponents();
        jTextFieldCodigo.setEditable(false);
        jTextFieldData.setEditable(false);
        
        BotaoCadastrar.setEnabled(false);
        BotaoLiberar.setEnabled(false);
        BotaoEditar.setEnabled(false);
        
        
        habilitaCampos(false);
       
        Modelo = (DefaultTableModel)Tabela.getModel();
        
        jTextFieldData.setText(VerificadoresECorretores.retornoDeDataAtual());
        
        habilitaTudo(false);
        
        FuncionarioC = new FuncionarioController();
        
        FuncionarioB = new FuncionarioBeans();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jSeparatorCodigo = new javax.swing.JSeparator();
        jLabelCargo = new javax.swing.JLabel();
        jComboCargo = new javax.swing.JComboBox();
        jLabelPermissao = new javax.swing.JLabel();
        jComboPermissao = new javax.swing.JComboBox();
        jTextFieldData = new javax.swing.JTextField();
        jLabelData = new javax.swing.JLabel();
        jSeparatorPesquisar = new javax.swing.JSeparator();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jLabelPesquisar = new javax.swing.JLabel();
        jSeparatorFormulario = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jSeparatorBotoes = new javax.swing.JSeparator();
        BotaoNovo = new javax.swing.JButton();
        BotaoCadastrar = new javax.swing.JButton();
        BotaoLiberar = new javax.swing.JButton();
        BotaoEditar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Manutenção de Funcionários");
        getContentPane().setLayout(null);

        jLabelCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCodigo.setText("Código");
        getContentPane().add(jLabelCodigo);
        jLabelCodigo.setBounds(0, 0, 440, 17);

        jTextFieldCodigo.setEditable(false);
        jTextFieldCodigo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldCodigo.setForeground(new java.awt.Color(255, 51, 51));
        jTextFieldCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCodigo.setDisabledTextColor(new java.awt.Color(255, 0, 51));
        jTextFieldCodigo.setEnabled(false);
        jTextFieldCodigo.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(0, 20, 440, 21);

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(63, 60, 377, 30);

        jLabelNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNome.setText("Nome:");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(0, 73, 53, 17);
        getContentPane().add(jSeparatorCodigo);
        jSeparatorCodigo.setBounds(0, 51, 440, 2);

        jLabelCargo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelCargo.setText("Cargo:");
        getContentPane().add(jLabelCargo);
        jLabelCargo.setBounds(0, 109, 53, 17);

        jComboCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um cargo...", "Atendente", "Pizzaiolo(a)", "Gerente" }));
        jComboCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCargoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboCargo);
        jComboCargo.setBounds(63, 108, 377, 23);

        jLabelPermissao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPermissao.setText("Permissão:");
        getContentPane().add(jLabelPermissao);
        jLabelPermissao.setBounds(0, 154, 77, 17);

        jComboPermissao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma permissão...", "AT", "PZ", "SUPER" }));
        jComboPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPermissaoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboPermissao);
        jComboPermissao.setBounds(81, 153, 160, 23);

        jTextFieldData.setEditable(false);
        jTextFieldData.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldData);
        jTextFieldData.setBounds(310, 143, 130, 40);

        jLabelData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dataCalendario.png"))); // NOI18N
        getContentPane().add(jLabelData);
        jLabelData.setBounds(250, 140, 50, 40);
        getContentPane().add(jSeparatorPesquisar);
        jSeparatorPesquisar.setBounds(10, 247, 430, 2);

        jTextFieldPesquisar.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldPesquisar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });
        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(94, 206, 346, 30);

        jLabelPesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        getContentPane().add(jLabelPesquisar);
        jLabelPesquisar.setBounds(40, 196, 50, 40);
        getContentPane().add(jSeparatorFormulario);
        jSeparatorFormulario.setBounds(0, 189, 440, 2);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Cargo", "Permissão", "Data do cadastro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.getTableHeader().setReorderingAllowed(false);
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabelaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(0).setResizable(false);
            Tabela.getColumnModel().getColumn(1).setResizable(false);
            Tabela.getColumnModel().getColumn(2).setResizable(false);
            Tabela.getColumnModel().getColumn(3).setResizable(false);
            Tabela.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 267, 440, 120);
        getContentPane().add(jSeparatorBotoes);
        jSeparatorBotoes.setBounds(0, 398, 440, 2);

        BotaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        BotaoNovo.setToolTipText("Habilita o formulário para receber novos dados");
        BotaoNovo.setAutoscrolls(true);
        BotaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovoActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoNovo);
        BotaoNovo.setBounds(40, 430, 50, 49);

        BotaoCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvarV2.png"))); // NOI18N
        BotaoCadastrar.setToolTipText("Cadastro de um novo cliente");
        BotaoCadastrar.setAutoscrolls(true);
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCadastrar);
        BotaoCadastrar.setBounds(100, 430, 50, 49);

        BotaoLiberar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/liberarParaEditar.png"))); // NOI18N
        BotaoLiberar.setToolTipText("Libera os campos para edição");
        BotaoLiberar.setAutoscrolls(true);
        BotaoLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLiberarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoLiberar);
        BotaoLiberar.setBounds(160, 430, 50, 49);

        BotaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        BotaoEditar.setToolTipText("Para editar alguma informação do cliente");
        BotaoEditar.setAutoscrolls(true);
        BotaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEditar);
        BotaoEditar.setBounds(220, 430, 52, 49);

        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar.png"))); // NOI18N
        jButtonFechar.setAutoscrolls(true);
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFechar);
        jButtonFechar.setBounds(280, 430, 50, 50);

        setBounds(0, 0, 450, 532);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jComboCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboCargoActionPerformed

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    private void jTextFieldPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarKeyPressed

    private void jTextFieldPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyReleased
        BotaoCadastrar.setEnabled(false);
        BotaoLiberar.setEnabled(true);
        BotaoEditar.setEnabled(true);
        
        Modelo.setNumRows(0);
        FuncionarioC.controlePesquisa(jTextFieldPesquisar.getText(), Modelo);
    }//GEN-LAST:event_jTextFieldPesquisarKeyReleased

    private void TabelaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMousePressed
        FuncionarioB = FuncionarioC.controlePreenchimento(Integer.parseInt(Modelo.getValueAt(Tabela.getSelectedRow(), 0).toString()));
        jTextFieldCodigo.setText(FuncionarioB.getFun_Codigo() + "");
        jTextFieldNome.setText(FuncionarioB.getFun_Nome()+ "");
        jComboCargo.setSelectedItem(FuncionarioB.getFun_Cargo() + "");
        jComboPermissao.setSelectedItem(FuncionarioB.getFun_Permissao() + "");
        jTextFieldData.setText(FuncionarioB.getFun_DataCad() + "");
    }//GEN-LAST:event_TabelaMousePressed

    private void jComboPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPermissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboPermissaoActionPerformed

    private void BotaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoActionPerformed
        Modelo.setRowCount(0);  //Limpa tabela
        BotaoCadastrar.setEnabled(true);
        BotaoLiberar.setEnabled(false);
        BotaoEditar.setEnabled(false);
        
        jTextFieldData.setText(VerificadoresECorretores.retornoDeDataAtual());
        
        habilitaCampos(true);
        jTextFieldNome.requestFocus(); // Foco no nome
        jTextFieldCodigo.setText(FuncionarioC.controleDeCodigo());
        limpaNovo();
    }//GEN-LAST:event_BotaoNovoActionPerformed

    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarActionPerformed
        //Cadastrar
        capturaBeans();
        if(FuncionarioC.verificaDados(FuncionarioB, jComboCargo.getSelectedIndex(), jComboPermissao.getSelectedIndex())) {
            limpaNovo();
            habilitaTudo(false);
        }
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    private void BotaoLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLiberarActionPerformed
        // TODO add your handling code here:
        BotaoCadastrar.setEnabled(false);
        BotaoEditar.setEnabled(true);
        
        habilitaCampos(true);
        jTextFieldNome.requestFocus();
    }//GEN-LAST:event_BotaoLiberarActionPerformed

    private void BotaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditarActionPerformed
        // TODO add your handling code here:
        capturaBeans();
        if(FuncionarioC.verificaDadosParaEditar(FuncionarioB,jComboCargo.getSelectedIndex(),jComboPermissao.getSelectedIndex())) {
            limparTudo();
            habilitaCampos(false);
        }
    }//GEN-LAST:event_BotaoEditarActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JButton BotaoEditar;
    private javax.swing.JButton BotaoLiberar;
    private javax.swing.JButton BotaoNovo;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JComboBox jComboCargo;
    private javax.swing.JComboBox jComboPermissao;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPermissao;
    private javax.swing.JLabel jLabelPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparatorBotoes;
    private javax.swing.JSeparator jSeparatorCodigo;
    private javax.swing.JSeparator jSeparatorFormulario;
    private javax.swing.JSeparator jSeparatorPesquisar;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables

final void habilitaTudo(boolean Valor) {
     jTextFieldNome.setEditable(Valor);
     jComboCargo.setEnabled(Valor);
     jComboPermissao.setEnabled(Valor);
    }

final void limpaNovo() {
    jTextFieldNome.setText("");
    jComboCargo.setSelectedIndex(0);
    jComboPermissao.setSelectedIndex(0);
    }

final void limparTudo() {
    jTextFieldCodigo.setText("");
    jTextFieldNome.setText("");
    jComboCargo.setSelectedIndex(0);
    jComboPermissao.setSelectedIndex(0);
    jTextFieldData.setText("");
}

final FuncionarioBeans capturaBeans() {
    FuncionarioB.setFun_Codigo(Integer.parseInt(jTextFieldCodigo.getText()));
    FuncionarioB.setFun_Nome(jTextFieldNome.getText());
    FuncionarioB.setFun_Cargo(jComboCargo.getSelectedItem().toString());
    FuncionarioB.setFun_Permissao(jComboPermissao.getSelectedItem().toString());
    FuncionarioB.setFun_DataCad(jTextFieldData.getText());
    
    return FuncionarioB;
    
}

  final void habilitaCampos(boolean Valor) {
    jTextFieldNome.setEditable(Valor);
     jComboCargo.setEnabled(Valor);
     jComboPermissao.setEnabled(Valor);
    }
}
