/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.UsuarioBeans;
import controller.UsuarioController;
import dao.UsuarioDAO;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import utilitarios.VerificadoresECorretores;
import javax.swing.table.TableColumnModel;


/**
 *
 * @author linux
 */
public class LoginGUI extends javax.swing.JInternalFrame {

    Connection con = null;
    
    UsuarioBeans UsuarioB; // Criando o bean
    UsuarioController UsuarioC; // criando o controller
    DefaultTableModel Modelo; //Classe abstrata da jTable fica mais fácil trabalhar
    UsuarioDAO UsuarioD;
    
    /**
     * Creates new form LoginUsuarioGUI
     */
    public LoginGUI() {
        initComponents();
        
        BotaoCadastrar.setEnabled(false);
        jButtonLiberar.setEnabled(false);
        BotaoEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextFieldCodigo.setEditable(false);
        jComboTipo.setEditable(false);
        jTextFieldData.setEditable(false); //Desabilita campo data
        
        habilitaCampos(false);
        
        UsuarioD = new UsuarioDAO();
        UsuarioB = new UsuarioBeans();  //Instanciando UsuarioBeans
        UsuarioC = new UsuarioController(); //Instanciando UsuarioBeans
        Modelo = (DefaultTableModel)Tabela.getModel();//No contrutor instanciando tabela
        jTextFieldData.setText(VerificadoresECorretores.retornoDeDataAtual());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelData = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        BotaoNovo = new javax.swing.JButton();
        BotaoCadastrar = new javax.swing.JButton();
        jButtonLiberar = new javax.swing.JButton();
        BotaoEditar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPesquisar = new javax.swing.JLabel();
        jButtonExcluir = new javax.swing.JButton();
        jLabelTipo = new javax.swing.JLabel();
        jLabelConfirmaSenha = new javax.swing.JLabel();
        jPasswordFieldConfirmaSenha = new javax.swing.JPasswordField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jComboTipo = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Usuários");
        getContentPane().setLayout(null);

        jLabelCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCodigo.setText("Código");
        getContentPane().add(jLabelCodigo);
        jLabelCodigo.setBounds(0, 38, 430, 17);

        jTextFieldCodigo.setEditable(false);
        jTextFieldCodigo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldCodigo.setForeground(new java.awt.Color(255, 51, 51));
        jTextFieldCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCodigo.setDisabledTextColor(new java.awt.Color(255, 0, 51));
        jTextFieldCodigo.setEnabled(false);
        jTextFieldCodigo.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(0, 58, 430, 21);

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(70, 100, 140, 30);

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(70, 180, 360, 30);

        jLabelData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dataCalendario.png"))); // NOI18N
        getContentPane().add(jLabelData);
        jLabelData.setBounds(190, 220, 50, 40);
        getContentPane().add(jTextFieldData);
        jTextFieldData.setBounds(250, 218, 180, 30);

        jTextFieldPesquisar.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldPesquisar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });
        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(80, 268, 350, 30);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Usuário", "Senha", "Tipo", "E-mail", "Data do Cadastro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.getTableHeader().setReorderingAllowed(false);
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabelaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(0).setResizable(false);
            Tabela.getColumnModel().getColumn(1).setResizable(false);
            Tabela.getColumnModel().getColumn(2).setMinWidth(0);
            Tabela.getColumnModel().getColumn(2).setPreferredWidth(0);
            Tabela.getColumnModel().getColumn(2).setMaxWidth(0);
            Tabela.getColumnModel().getColumn(3).setResizable(false);
            Tabela.getColumnModel().getColumn(4).setResizable(false);
            Tabela.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 318, 440, 120);

        BotaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        BotaoNovo.setToolTipText("Habilita o formulário para receber novos dados");
        BotaoNovo.setAutoscrolls(true);
        BotaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovoActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoNovo);
        BotaoNovo.setBounds(40, 460, 50, 49);

        BotaoCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvarV2.png"))); // NOI18N
        BotaoCadastrar.setToolTipText("Cadastro de um novo cliente");
        BotaoCadastrar.setAutoscrolls(true);
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCadastrar);
        BotaoCadastrar.setBounds(100, 460, 50, 49);

        jButtonLiberar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/liberarParaEditar.png"))); // NOI18N
        jButtonLiberar.setToolTipText("Libera os campos para edição");
        jButtonLiberar.setAutoscrolls(true);
        jButtonLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiberarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLiberar);
        jButtonLiberar.setBounds(160, 460, 50, 49);

        BotaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        BotaoEditar.setToolTipText("Para editar alguma informação do cliente");
        BotaoEditar.setAutoscrolls(true);
        BotaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEditar);
        BotaoEditar.setBounds(220, 460, 52, 49);

        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar.png"))); // NOI18N
        jButtonFechar.setAutoscrolls(true);
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFechar);
        jButtonFechar.setBounds(280, 460, 50, 50);

        jLabelUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelUsuario.setText("Usuário:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(0, 108, 76, 17);

        jLabelSenha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(0, 148, 62, 17);

        jLabelEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelEmail.setText("E-mail:");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(0, 188, 50, 17);

        jLabelPesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        getContentPane().add(jLabelPesquisar);
        jLabelPesquisar.setBounds(20, 250, 50, 50);

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir2.png"))); // NOI18N
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(380, 460, 50, 49);

        jLabelTipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTipo.setText("Tipo:");
        getContentPane().add(jLabelTipo);
        jLabelTipo.setBounds(220, 100, 40, 17);

        jLabelConfirmaSenha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelConfirmaSenha.setText("Conf.");
        getContentPane().add(jLabelConfirmaSenha);
        jLabelConfirmaSenha.setBounds(220, 140, 50, 17);

        jPasswordFieldConfirmaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldConfirmaSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldConfirmaSenha);
        jPasswordFieldConfirmaSenha.setBounds(280, 140, 150, 30);
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(70, 140, 140, 30);

        jComboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um usuário...", "AT", "PZ", "SUPER" }));
        jComboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboTipo);
        jComboTipo.setBounds(270, 100, 160, 23);

        setBounds(0, 0, 461, 548);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    private void jTextFieldPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarKeyPressed

    private void jTextFieldPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyReleased
        BotaoCadastrar.setEnabled(false);
        jButtonLiberar.setEnabled(true);
        BotaoEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        
        Modelo.setNumRows(0);
        UsuarioC.controlePesquisa(jTextFieldPesquisar.getText(), Modelo);
    }//GEN-LAST:event_jTextFieldPesquisarKeyReleased

    private void TabelaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMousePressed
             
        
        UsuarioB = UsuarioC.controlePreenchimento(Integer.parseInt(Modelo.getValueAt(Tabela.getSelectedRow(), 0).toString()));
        
        jTextFieldCodigo.setText(UsuarioB.getId() + "");
        jTextFieldUsuario.setText(UsuarioB.getUsuario() + "");
        jPasswordFieldSenha.setText(UsuarioB.getSenha() + "");
        jComboTipo.setSelectedItem(UsuarioB.getTipo() + "");
        jTextFieldEmail.setText(UsuarioB.getEmail() + "");
        jTextFieldData.setText(UsuarioB.getDataCad() + "");
    }//GEN-LAST:event_TabelaMousePressed

    private void BotaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoActionPerformed
        Modelo.setRowCount(0);  //Limpa tabela
        BotaoCadastrar.setEnabled(true);
        jButtonLiberar.setEnabled(false);
        BotaoEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextFieldData.setText(VerificadoresECorretores.retornoDeDataAtual());
        habilitaCampos(true);jTextFieldUsuario.requestFocus();
        jTextFieldUsuario.requestFocus(); // Foco no nome
        jTextFieldCodigo.setText(UsuarioC.controleDeCodigo());
        limpaNovo();
    }//GEN-LAST:event_BotaoNovoActionPerformed

    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarActionPerformed
        //Cadastrar
        try {
            populaUsuarioBeans();
            
            if(jPasswordFieldConfirmaSenha.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "O campo confirma senha está em branco!!!");
                jPasswordFieldConfirmaSenha.requestFocus();
                
            } else if((jPasswordFieldSenha.getText()).equals(jPasswordFieldConfirmaSenha.getText())) {
                if(UsuarioC.verificarDados(UsuarioB, jComboTipo.getSelectedIndex()));
                limpaTudo();
                habilitaCampos(false);
                
            }else {
                
                JOptionPane.showMessageDialog(null, "O campo senha e confirma senha têm de ser iguais!!!");
                jPasswordFieldConfirmaSenha.requestFocus();
            }
        
        } catch (Exception ex) {
            System.err.println("I/O error: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, ex);
            JOptionPane.showMessageDialog(null, "Impossível Cadastrar2","Erro de SQL!!!", 0, new ImageIcon("Imagens/cancelar.png"));
            Logger.getLogger(UsuarioDAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    private void jButtonLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiberarActionPerformed
        // TODO add your handling code here:
        BotaoEditar.setEnabled(true);
                
        habilitaCampos(true);
        jTextFieldUsuario.requestFocus();
    }//GEN-LAST:event_jButtonLiberarActionPerformed

    private void BotaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditarActionPerformed
        // TODO add your handling code here:
        populaUsuarioBeans();
        if(UsuarioC.verificarDadosParaEditar(UsuarioB)) {
            limpaTudo();
            habilitaCampos(false);
        }
    }//GEN-LAST:event_BotaoEditarActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
              
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja excluir?");
              if(resposta == 0) {
                
                limpaTudo();
                Modelo.removeRow(Tabela.getSelectedRow());
                UsuarioD.excluirUsuario(UsuarioB);
              }
        
 
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jComboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoActionPerformed

    private void jPasswordFieldConfirmaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldConfirmaSenhaActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JButton BotaoEditar;
    private javax.swing.JButton BotaoNovo;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLiberar;
    private javax.swing.JComboBox jComboTipo;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelConfirmaSenha;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelPesquisar;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordFieldConfirmaSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables

final void habilitaCampos(boolean Valor) {
    jTextFieldUsuario.setEditable(Valor);
    jComboTipo.setEnabled(Valor);
    jPasswordFieldSenha.setEditable(Valor);
    jPasswordFieldConfirmaSenha.setEditable(Valor);
    jTextFieldEmail.setEditable(Valor);
    }
    
    final void populaUsuarioBeans() {
        UsuarioB.setUsuario(jTextFieldUsuario.getText());
        UsuarioB.setSenha(jPasswordFieldSenha.getText());
        UsuarioB.setTipo(jComboTipo.getSelectedItem().toString());
        UsuarioB.setEmail(jTextFieldEmail.getText());
        UsuarioB.setDataCad(jTextFieldData.getText());
    }
    
    final void limpaTudo() {
        jTextFieldCodigo.setText("");
        jTextFieldUsuario.setText("");
        jComboTipo.setSelectedIndex(0);
        jPasswordFieldSenha.setText("");
        jPasswordFieldConfirmaSenha.setText("");
        jTextFieldEmail.setText("");
        jTextFieldData.setText("");
    }
    
    final void limpaNovo() {
        jTextFieldUsuario.setText("");
        jComboTipo.setSelectedIndex(0);
        jPasswordFieldSenha.setText("");
        jPasswordFieldConfirmaSenha.setText("");
        jTextFieldEmail.setText("");
     }   
}
