/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import utilitarios.VerificadoresECorretores;
import beans.ClienteBeans;
import beans.PedidoBeans;
import controller.ClienteController;
import controller.PedidoController;
import java.util.List;
import java.util.ArrayList;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.ListSelectionModel;
import java.util.Date;
import java.text.SimpleDateFormat;
import beans.FuncionarioBeans;
import beans.EntregadorBeans;
import controller.FuncionarioController;
import controller.EntregadorController;

/**
 *
 * @author linux
 */
public class PedidoGUI extends javax.swing.JInternalFrame {

    MaskFormatter FormatoTelefone;
    ClienteBeans ClienteB;
    ClienteController ClienteC; 
    List<String> Lista;
    DefaultTableModel Modelo;
    List<String> ListaDeItens;
    List<String> ListaDeClientes;
    DecimalFormat FormatoDecimal;
    PedidoController PedidoC;
    PedidoBeans PedidoB;
    FuncionarioBeans FuncionarioB;
    EntregadorBeans EntregadorB;
    Date DataAtual;
    SimpleDateFormat FormatoData, FormatoHora;
    
    String CodigoFuncionario;
    String CodigoEntregador;
    
    /**
     * Creates new form PedidoGUI
     */
    public PedidoGUI() {
        initComponents();
        
        habilitaCampos(false);
        FormatoDecimal = new DecimalFormat("0.00");
        ClienteB = new ClienteBeans();
        ClienteC = new ClienteController();
        Lista = new ArrayList<>();
        jTabbedPanePai.setEnabledAt(1, false);
        Modelo = (DefaultTableModel)Tabela.getModel();
        PedidoC = new PedidoController();
        PedidoB = new PedidoBeans();
        FormatoDecimal = new DecimalFormat("0.00");
        FormatoData = new SimpleDateFormat("yyyy-MM-dd");
        FormatoHora = new SimpleDateFormat("HH:mm:ss");
        
        ListaDeClientes = new ArrayList<>();
        ListaDeItens = new ArrayList<>();
        
        jTextFieldCliente.setEditable(false);
        jTextFieldValor.setEditable(false);
        jTextFieldCodigoItem.setEditable(false);
        jButtonFinalizar.setEnabled(false);
        
        jTabbedPanePai.setEnabledAt(1, false);
        
        jButtonContinuarPedido.setEnabled(false);
        
        Tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        jTextFieldTotal.setEditable(false);
        
        this.CodigoFuncionario = CodigoFuncionario;
        this.CodigoEntregador = CodigoEntregador;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanePai = new javax.swing.JTabbedPane();
        jPanelCliente = new javax.swing.JPanel();
        jButtonPesquisar = new javax.swing.JButton();
        jComboBoxPesquisar = new javax.swing.JComboBox<>();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jLabelRua = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        try {
            FormatoTelefone = new MaskFormatter("(##)####-####");
        }catch(Exception Erro) {
            JOptionPane.showMessageDialog(null, "Impossível formatar campo Telefone!!!", "Erro de formatação", 0);
        }
        jFormattedTextFieldTelefone = new JFormattedTextField(FormatoTelefone);
        ;
        jLabelData = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jButtonContinuarPedido = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jPanelPedido = new javax.swing.JPanel();
        jTextFieldCliente = new javax.swing.JTextField();
        jLabelItem = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jLabelCodigoItem = new javax.swing.JLabel();
        jComboBoxSelecionar = new javax.swing.JComboBox<>();
        jButtonValor = new javax.swing.JButton();
        jLabelItem1 = new javax.swing.JLabel();
        jTextFieldItem = new javax.swing.JTextField();
        jLabelItemQuantidade = new javax.swing.JLabel();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jButtonAcrescentar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jButtonFinalizar = new javax.swing.JButton();
        jButtonCalcular = new javax.swing.JButton();
        jLabelSelecionar1 = new javax.swing.JLabel();
        jTextFieldCodigoItem = new javax.swing.JTextField();
        jButtonFecharPedido = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pedido");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jComboBoxPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPesquisarActionPerformed(evt);
            }
        });

        jLabelCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCodigo.setText("Código");

        jTextFieldCodigo.setEditable(false);
        jTextFieldCodigo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldCodigo.setForeground(new java.awt.Color(255, 51, 51));
        jTextFieldCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCodigo.setDisabledTextColor(new java.awt.Color(255, 0, 51));
        jTextFieldCodigo.setEnabled(false);
        jTextFieldCodigo.setSelectionColor(new java.awt.Color(255, 255, 255));

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabelNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNome.setText("Nome:");

        jLabelRua.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRua.setText("Rua:");

        jLabelBairro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelBairro.setText("Bairro:");

        jLabelTelefone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telefone.png"))); // NOI18N

        jLabelData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dataCalendario.png"))); // NOI18N

        jTextFieldData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataActionPerformed(evt);
            }
        });

        jButtonContinuarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/continuarPedido.png"))); // NOI18N
        jButtonContinuarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarPedidoActionPerformed(evt);
            }
        });

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelClienteLayout.createSequentialGroup()
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelClienteLayout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addGap(36, 36, 36)
                        .addComponent(jTextFieldNome))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelClienteLayout.createSequentialGroup()
                        .addComponent(jLabelRua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jTextFieldRua))
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelClienteLayout.createSequentialGroup()
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelClienteLayout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(jTextFieldBairro))
                                .addGroup(jPanelClienteLayout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonContinuarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanelClienteLayout.createSequentialGroup()
                                            .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(41, 41, 41)
                                            .addComponent(jLabelData)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClienteLayout.createSequentialGroup()
                                .addGap(651, 651, 651)
                                .addComponent(jButtonFechar)
                                .addGap(65, 65, 65)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jLabelCodigo)
                .addGap(3, 3, 3)
                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabelNome))
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelRua))
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelBairro))
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTelefone)
                            .addGroup(jPanelClienteLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelClienteLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jButtonFechar)
                        .addGap(9, 9, 9)
                        .addComponent(jButtonContinuarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabelData)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPanePai.addTab("Cliente", jPanelCliente);

        jLabelItem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelItem.setText("Item:");

        jTextFieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorActionPerformed(evt);
            }
        });

        jLabelCodigoItem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelCodigoItem.setText("Código:");

        jComboBoxSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelecionarActionPerformed(evt);
            }
        });

        jButtonValor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cifraoValor.png"))); // NOI18N
        jButtonValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValorActionPerformed(evt);
            }
        });

        jLabelItem1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelItem1.setText("valor:");

        jTextFieldItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemActionPerformed(evt);
            }
        });

        jLabelItemQuantidade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelItemQuantidade.setText("Quantidade: ");

        jTextFieldQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldQuantidadeFocusLost(evt);
            }
        });
        jTextFieldQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantidadeActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Quantidade", "Valor Unit", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.getTableHeader().setReorderingAllowed(false);
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabelaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(0).setResizable(false);
            Tabela.getColumnModel().getColumn(1).setResizable(false);
            Tabela.getColumnModel().getColumn(2).setResizable(false);
            Tabela.getColumnModel().getColumn(3).setResizable(false);
            Tabela.getColumnModel().getColumn(4).setResizable(false);
        }

        jButtonAcrescentar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais.png"))); // NOI18N
        jButtonAcrescentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcrescentarActionPerformed(evt);
            }
        });

        jButtonRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menos.png"))); // NOI18N
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jLabelTotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTotal.setText("Total:");

        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });

        jButtonFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/finalizarPedido.png"))); // NOI18N
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });

        jButtonCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculadora.png"))); // NOI18N
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jLabelSelecionar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelSelecionar1.setText("Selecionar: ");

        jTextFieldCodigoItem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCodigoItemFocusLost(evt);
            }
        });
        jTextFieldCodigoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoItemActionPerformed(evt);
            }
        });

        jButtonFecharPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar.png"))); // NOI18N
        jButtonFecharPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPedidoLayout = new javax.swing.GroupLayout(jPanelPedido);
        jPanelPedido.setLayout(jPanelPedidoLayout);
        jPanelPedidoLayout.setHorizontalGroup(
            jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPedidoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldCliente)
                        .addGroup(jPanelPedidoLayout.createSequentialGroup()
                            .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelPedidoLayout.createSequentialGroup()
                                    .addComponent(jLabelItem)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(119, 119, 119)
                                    .addComponent(jComboBoxSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelPedidoLayout.createSequentialGroup()
                                    .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelPedidoLayout.createSequentialGroup()
                                            .addComponent(jButtonValor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelPedidoLayout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jButtonAcrescentar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelItemQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelPedidoLayout.createSequentialGroup()
                                            .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelPedidoLayout.createSequentialGroup()
                                            .addComponent(jLabelCodigoItem)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldCodigoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(38, 38, 38)))
                    .addGroup(jPanelPedidoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPedidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonFecharPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPedidoLayout.createSequentialGroup()
                    .addGap(305, 305, 305)
                    .addComponent(jLabelSelecionar1)
                    .addContainerGap(343, Short.MAX_VALUE)))
        );
        jPanelPedidoLayout.setVerticalGroup(
            jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPedidoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelItem)
                            .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPedidoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelItem1)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelItemQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodigoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodigoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAcrescentar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFecharPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
            .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPedidoLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jLabelSelecionar1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(450, Short.MAX_VALUE)))
        );

        jTabbedPanePai.addTab("Pedido", jPanelPedido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPanePai, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanePai, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonContinuarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarPedidoActionPerformed
      jTabbedPanePai.setEnabledAt(1, true);
      jTabbedPanePai.setEnabledAt(0, false);
      jTabbedPanePai.setSelectedIndex(1);
      jTextFieldCliente.setText(jTextFieldNome.getText());
    }//GEN-LAST:event_jButtonContinuarPedidoActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
       dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jTextFieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorActionPerformed
       
    }//GEN-LAST:event_jTextFieldValorActionPerformed

    private void jTextFieldItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemActionPerformed
       jTextFieldValor.setText("");
       jTextFieldQuantidade.setText("");
       jTextFieldCodigoItem.setText("");
       jComboBoxSelecionar.removeAllItems();
       ListaDeItens.clear();
       PedidoC.controleDeItens(jTextFieldItem.getText(), ListaDeItens);
       for(String S : ListaDeItens) {
           jComboBoxSelecionar.addItem(S);
       }
    }//GEN-LAST:event_jTextFieldItemActionPerformed

    private void jTextFieldQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeActionPerformed
        
    }//GEN-LAST:event_jTextFieldQuantidadeActionPerformed

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        jButtonContinuarPedido.setEnabled(true);
        jComboBoxPesquisar.removeAllItems();
        Lista.clear();
        String Pesquisa = JOptionPane.showInputDialog(null, "Digite o nome do cliente", "PESQUISA DE CLIENTE", 3);
        ClienteC.controlePesquisa(Pesquisa, Lista);
        for (String S : Lista) {
            jComboBoxPesquisar.addItem(S);
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonFecharPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharPedidoActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFecharPedidoActionPerformed

    private void TabelaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMousePressed
//        ClienteB = ClienteC.controlePreenchimento(Integer.parseInt(Modelo));
    }//GEN-LAST:event_TabelaMousePressed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        Modelo.removeRow(Tabela.getSelectedRow());
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        double TotalDoPedido = 0;
        for(int i = 0; i < Tabela.getRowCount(); i++) {
            TotalDoPedido += Double.parseDouble(Modelo.getValueAt(i, 4).toString());
        }
        jTextFieldTotal.setText(FormatoDecimal.format(TotalDoPedido).replace(",", "."));
        populaBeans();
        if(TotalDoPedido > 0 ) {
            jButtonFinalizar.setEnabled(true);
            jButtonAcrescentar.setEnabled(false);
            jButtonRemover.setEnabled(false);
            jButtonCalcular.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        PedidoC.controleDePedido(jTextFieldCodigo.getText(), CodigoFuncionario, CodigoEntregador, jTextFieldTotal.getText(), Tabela.getRowCount(), FuncionarioB, EntregadorB, PedidoB);
        limpaEFinaliza();
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    private void jButtonValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValorActionPerformed
        jTextFieldValor.setText(PedidoC.controleDeValor(jComboBoxSelecionar.getSelectedItem().toString()) + "");
        jTextFieldCodigoItem.setText(PedidoC.controleDeCodigo(jComboBoxSelecionar.getSelectedItem().toString()) + "");
        
    }//GEN-LAST:event_jButtonValorActionPerformed

    private void jComboBoxSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelecionarActionPerformed
        jTextFieldValor.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldCodigoItem.setText("");
    }//GEN-LAST:event_jComboBoxSelecionarActionPerformed

    private void jTextFieldQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeFocusLost
        try {
            int x = Integer.parseInt(jTextFieldQuantidade.getText());
        if(x == 0) {
            JOptionPane.showMessageDialog(null, "Campo quantidade não pode ser zero!!!","Erro de preenchimento!!!", 0, new ImageIcon("Imagens/cancelar.png"));
            jTextFieldQuantidade.setText("");
            jTextFieldQuantidade.requestFocus();
        }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Campo quantidade dever ter um número inteiro!!!","Erro de preenchimento!!!", 0, new ImageIcon("Imagens/cancelar.png"));
            jTextFieldQuantidade.setText("");
            jTextFieldQuantidade.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldQuantidadeFocusLost

    private void jTextFieldCodigoItemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCodigoItemFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoItemFocusLost

    private void jTextFieldCodigoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoItemActionPerformed

    private void jButtonAcrescentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcrescentarActionPerformed
        if(PedidoC.verificaItens(jTextFieldValor.getText(), jTextFieldQuantidade.getText(), jTextFieldCodigoItem.getText(), jComboBoxSelecionar.getSelectedItem().toString())) {
            double Total = Double.parseDouble(jTextFieldValor.getText()) * Integer.parseInt(jTextFieldQuantidade.getText());


            Modelo.addRow(new Object[] {jTextFieldCodigoItem.getText(),
            jComboBoxSelecionar.getSelectedItem(), jTextFieldValor.getText(),
            jTextFieldQuantidade.getText(), FormatoDecimal.format(Total).replace(",", ".")});
            limpaItens();
        }
    }//GEN-LAST:event_jButtonAcrescentarActionPerformed

    private void jComboBoxPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPesquisarActionPerformed
        if(!(jComboBoxPesquisar.getSelectedItem() == null)) {
            String Cod = jComboBoxPesquisar.getSelectedItem().toString();
            Cod = Cod.substring(0, Cod.indexOf(" "));
            ClienteB = ClienteC.controlePreenchimento(Integer.parseInt(Cod));
            jTextFieldCodigo.setText(ClienteB.getCli_Codigo() + "");
            jTextFieldNome.setText(ClienteB.getCli_Nome() + "");
            jTextFieldRua.setText(ClienteB.getCli_Rua() + "");
            jTextFieldBairro.setText(ClienteB.getCli_Bairro() + "");
            jFormattedTextFieldTelefone.setText(ClienteB.getCli_Telefone() + "");
            jTextFieldData.setText(ClienteB.getCli_DataCad() + "");

        }
    }//GEN-LAST:event_jComboBoxPesquisarActionPerformed

    private void jTextFieldDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton jButtonAcrescentar;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonContinuarPedido;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonFecharPedido;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JButton jButtonValor;
    private javax.swing.JComboBox<String> jComboBoxPesquisar;
    private javax.swing.JComboBox<String> jComboBoxSelecionar;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCodigoItem;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelItem;
    private javax.swing.JLabel jLabelItem1;
    private javax.swing.JLabel jLabelItemQuantidade;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelRua;
    private javax.swing.JLabel jLabelSelecionar1;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelPedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPanePai;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCodigoItem;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldItem;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldQuantidade;
    private javax.swing.JTextField jTextFieldRua;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables

final void habilitaCampos(boolean Valor) {
    jTextFieldCodigo.setEnabled(Valor);
    jTextFieldNome.setEditable(Valor);
    jTextFieldRua.setEditable(Valor);
    jFormattedTextFieldTelefone.setEditable(Valor);
    jTextFieldBairro.setEditable(Valor);
    jTextFieldData.setEditable(Valor);
    }

final void limpaItens() {
    jTextFieldItem.setText("");
    jTextFieldItem.setText("");
    jTextFieldQuantidade.setText("");
    jTextFieldValor.setText("");
    jComboBoxSelecionar.removeAllItems();
    }

final void limpaEFinaliza() {
    jTextFieldTotal.setText("");
    jButtonFinalizar.setEnabled(false);
    Modelo.setNumRows(0);
    jTextFieldCliente.setText("");
}

final void populaBeans() {
    DataAtual = new Date();
    PedidoB.setCodigoCliente(Integer.parseInt(jTextFieldCodigo.getText()));
    //PedidoB.setCodigoFuncionario(CodigoFuncionario);
    //PedidoB.setCodigoEntregador(0);
    PedidoB.setData(FormatoData.format(DataAtual));
    PedidoB.setHora(FormatoHora.format(DataAtual));
    PedidoB.setStatus("Pedido Aberto");
    PedidoB.setValor(Double.parseDouble(jTextFieldTotal.getText()));
    for(int i = 0; i < Tabela.getRowCount(); i++) {
        PedidoB.setCodCardapio(Integer.parseInt(Modelo.getValueAt(i, 0).toString()));
        PedidoB.setQuantidade(Integer.parseInt(Modelo.getValueAt(i, 3).toString()));
    }
}

}
